const express = require('express');
const path = require('path');
const indexRouter = require('./routes/index.router');
const app = express();
app.use(express.urlencoded({ extended: true }));
app.use(express.json());
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');
app.use('/', indexRouter);
module.exports = app;
